Areas/Admin/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CampChetek.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using CampChetek.Library;
using CampChetek.DataAccessLayer;

namespace CampChetek.Areas.Admin.Controllers
{
    [Route("[area]/[controller]/[action]")]
    [Area("Admin")]
    public class EventsController : Controller
    {
        private Persons context { get; set; }

        public EventsController(Persons ctx)
        {
            context = ctx;
        }
        //private DA _DA { get; set; }

        //public EventsController(IOptions<AppSettings> settings)
        //{
        //    _DA = new DataAccessLayer.DA(settings.Value.ConnectionStr);
        //}

        public IActionResult Calendar()
        {
            return View();
        }

        //[HttpGet]
        //public IActionResult GetCalendarEvents()
        //{
        //    var events = context.Houses.Select(e => new
        //    {
        //        eventId = e.ID,
        //        title = e.Title,
        //        description = e.RoomsId,
        //        StartTime = e.Start.ToString("MM/dd/yyyy h: mm A"),
        //        EndTime = e.End.ToString("MM/dd/yyyy h: mm A")
        //    });
        //    return new JsonResult(events);
        //}

        [HttpGet]
        public IActionResult GetCalendarEvents(string start, string end)
        {
            //start = DateTime.Now.ToString();
            //end = DateTime.Now.ToString();
            //List<GetCalendarEvents> events = _DA.GetCalendarEvents(start, end);


            //return Json(events);
            var eventsList = context.events.Select(e => new
            {
                id = e.event_id,
                title = e.title,
                description = e.description,
                start = e.event_start,
                end = e.event_end,
                allDay = e.all_day

            });


            return Json(eventsList);
        }

        [HttpPost]
        public IActionResult UpdateEvent([FromBody] GetCalendarEvents evt)
        {
            string message = String.Empty;

            //message = _DA.UpdateEvent(evt);

            return Json(new { message });
        }

        [HttpPost]
        public IActionResult AddEvent([FromBody] GetCalendarEvents evt)
        {
            string message = String.Empty;
            int eventId = 0;

            //message = _DA.AddEvent(evt, out eventId);

            return Json(new { message, eventId });
        }

        [HttpPost]
        public IActionResult DeleteEvent([FromBody] GetCalendarEvents evt)
        {
            string message = String.Empty;

            //message = _DA.DeleteEvent(evt.EventId);

            return Json(new { message });
        }
    }
}

Areas/Admin/Controllers/HousingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CampChetek.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using CampChetek.Library;
using CampChetek.DataAccessLayer;
using System.Net.Mail;

namespace CampChetek.Areas.Admin.Controllers
{
    [Route("[area]/[controller]/[action]")]
    [Area("Admin")]
    public class HousingController : Controller
    {
        private Persons context { get; set; }

        public HousingController(Persons ctx)
        {
            context = ctx;
        }

        [HttpGet]
        [Route("{orderby?}")]
        public IActionResult Dashboard(string orderby)
        {
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(orderby) ? "FirstNameDesc" : "";
            ViewBag.LastNameParm = orderby == "LastName" ? "lastNameDesc" : "LastName";
            ViewBag.RoomsIdParm = orderby == "RoomId" ? "roomIdDesc" : "RoomId";
            ViewBag.ArrivalDateParm = orderby == "ArrivalDate" ? "ArrivalDateDesc" : "ArrivalDate";
            ViewBag.DepartureDateParm = orderby == "DepartureDate" ? "DepartureDateDesc" : "DepartureDate";
            ViewBag.NumberGuestParm = orderby == "NumberGuest" ? "NumberGuestDesc" : "NumberGuest";
            ViewBag.BeddingParm = orderby == "Bedding" ? "BeddingDesc" : "Bedding";
            ViewBag.DateUpdateParm = orderby == "DateUpdate" ? "DateUpdateDesc" : "DateUpdate";

            var housing = from p in context.events select p;
            
            switch (orderby)
            {
                case "FirstNameDesc":
                    housing = housing.OrderByDescending(p => p.FirstName);
                    break;
                case "LastName":
                    housing = housing.OrderBy(s => s.LastName);
                    break;
                case "lastNameDesc":
                    housing = housing.OrderByDescending(p => p.LastName);
                    break;
                case "RoomId":
                    housing = housing.OrderBy(s => s.RoomsId);
                    break;
                case "roomIdDesc":
                    housing = housing.OrderByDescending(p => p.RoomsId);
                    break;
                case "ArrivalDate":
                    housing = housing.OrderBy(s => s.event_start);
                    break;
                case "ArrivalDateDesc":
                    housing = housing.OrderByDescending(p => p.event_start);
                    break;
                case "DepartureDate":
                    housing = housing.OrderBy(s => s.event_end);
                    break;
                case "DepartureDateDesc":
                    housing = housing.OrderByDescending(p => p.event_end);
                    break;
                case "NumberGuest":
                    housing = housing.OrderBy(s => s.NumberGuest);
                    break;
                case "NumberGuestDesc":
                    housing = housing.OrderByDescending(p => p.NumberGuest);
                    break;
                case "Bedding":
                    housing = housing.OrderBy(s => s.Bedding);
                    break;
                case "BeddingDesc":
                    housing = housing.OrderByDescending(p => p.Bedding);
                    break;
                case "DateUpdate":
                    housing = housing.OrderBy(s => s.DateUpdate);
                    break;
                case "DateUpdateDesc":
                    housing = housing.OrderByDescending(p => p.DateUpdate);
                    break;
                default:
                    housing = housing.OrderBy(s => s.FirstName);
                    break;
            }

            ViewBag.Bedding = context.beddings.OrderBy(b => b.Name).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.FirstName).ToList();
            ViewBag.Rooms = context.Room.OrderBy(p => p.Name).ToList();
            var session = new HousingSession(HttpContext.Session);
            string check = session.GetName();

            if (check != null)
            {
                return View(housing.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public IActionResult Detail(int id)
        {
            ViewBag.Bedding = context.beddings.OrderBy(b => b.Name).ToList();
            ViewBag.Rooms = context.Room.OrderBy(p => p.Name).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.FirstName).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.LastName).ToList();
            ViewBag.Reason = context.Reasons.OrderBy(r => r.Name).ToList();

            var housing = context.events.Find(id);
            return View(housing);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Bedding = context.beddings.OrderBy(b => b.Name).ToList();
            ViewBag.Rooms = context.Room.OrderBy(p => p.Name).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.FirstName).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.LastName).ToList();
            ViewBag.Reason = context.Reasons.OrderBy(r => r.Name).ToList();

            return View("Edit", new Models.Events());

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Bedding = context.beddings.OrderBy(b => b.Name).ToList();
            ViewBag.Rooms = context.Room.OrderBy(p => p.Name).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.FirstName).ToList();
            ViewBag.User = context.Users.OrderBy(u => u.LastName).ToList();
            ViewBag.Reason = context.Reasons.OrderBy(r => r.Name).ToList();

            var housing = context.events.Find(id);

            return View(housing);
        }

        [HttpPost]
        public IActionResult Edit(Models.Events housing)
        {

            if (ModelState.IsValid)
            {
                if (housing.event_id == 0)
                {
                    housing.title = housing.FirstName + " " + housing.LastName + " | Room: " + context.Room.Find(housing.RoomsId).Name.ToString();
                    housing.description = housing.FirstName + " " + housing.LastName + " | Bedding: " + context.beddings.Find(housing.BeddingId).Name.ToString() + " | Number Of Guest: " + housing.NumberGuest.ToString();
                    context.events.Add(housing);

                    string bcc = "danael@campchetek.org";
                    string to = housing.Email;
                    string subject = "Thank You For Your Housing Request";
                    string boby = "Thank You " + housing.FirstName + " we will get back to you soon about staying<br><br> " + housing.event_start.ToString("MM/dd/yyyy") + "-" + housing.event_end.ToString("MM/dd/yyyy") + ". ";
                    MailMessage mm = new MailMessage();
                    mm.To.Add(to);
                    mm.Subject = subject;
                    mm.Body = boby;
                    mm.From = new MailAddress("dannykluver1@gmail.com");
                    mm.Bcc.Add(bcc);
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                    smtp.Port = 587;
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtp.UseDefaultCredentials = false;
                    smtp.EnableSsl = true;
                    smtp.Credentials = new System.Net.NetworkCredential("dannykluver1@gmail.com", "HideMenu45");
                    smtp.Send(mm);
                    ViewBag.message = "The Mail Has Been Sent To " + housing.Email + " Successfully..!";
                }
                else
                {
                    if (housing.sendEmail == true)
                    {
                        string bcc = "danael@campchetek.org";
                        string to = housing.Email;
                        string subject = "Camp Chetek Booking Confirmation";
                        string boby = housing.FirstName + " " + housing.LastName + "<br>" + housing.Address + "<br>" + housing.City + " " + housing.State + " " + housing.Zip + "<br><br>" + "Thank You " + housing.FirstName + ", for your recent request for accommodation.<br><br>" + "Below are the details of your booking. Please take a moment to check them, and if there are any problems, please call us so we can correct our records.<br><br>" + "We look forward to welcoming you, and will do our utmost to make your stay with us an enjoyable and memorable experience.<br><br><hr>" + "Arriving: " + housing.event_start.ToString("MM/dd/yyyy") + "<br>" + "Leaving: " + housing.event_end.ToString("MM/dd/yyyy") + "<br>" + "Guests: " + housing.NumberGuest.ToString() + "<br>" + "Room: " + context.Room.Find(housing.RoomsId).Name.ToString() + "<br>" + "Bedding: " + context.beddings.Find(housing.BeddingId).Name.ToString() + "<br><hr>";
                        MailMessage mm = new MailMessage();
                        mm.To.Add(to);
                        mm.Subject = subject;
                        mm.Body = boby;
                        mm.From = new MailAddress("dannykluver1@gmail.com");
                        mm.Bcc.Add(bcc);
                        mm.IsBodyHtml = true;
                        SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                        smtp.Port = 587;
                        smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                        smtp.UseDefaultCredentials = false;
                        smtp.EnableSsl = true;
                        smtp.Credentials = new System.Net.NetworkCredential("dannykluver1@gmail.com", "HideMenu45");
                        smtp.Send(mm);

Areas/Admin/Views/Housing/Dashboard.cshtml
@model List<Events>
@{
    ViewData["Title"] = "Dashboard";
    var session = new HousingSession(Context.Session);

}
    <aside class="sidebar">
        <nav>
            <ul class="sidebar__nav">
                <li>
                    <a asp-area="Admin" asp-controller="Housing" asp-action="Dashboard" class="sidebar__nav__link">
                        <i class="mdi mdi-home-export-outline"></i>
                        <span class="sidebar__nav__text">Home</span>
                    </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Events" asp-action="Calendar" class="sidebar__nav__link">
                        <i class="mdi mdi-calendar-month"></i>
                        <span class="sidebar__nav__text">Calendar</span>
                    </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Housing" asp-action="Add" class="sidebar__nav__link">
                        <i class="mdi mdi-plus-outline"></i>
                        <span class="sidebar__nav__text">Add</span>
                    </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Housing" asp-action="RoomStatus" class="sidebar__nav__link">
                        <i class="mdi mdi-file-document-box"></i>
                        <span class="sidebar__nav__text">Room Status</span>
                    </a>
                </li>
                <li>
                   
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="sidebar__nav__link">

                        @if (session.GetName() == "DANAEL@CAMPCHETEK.ORG")
                        {
                            <i class="mdi mdi-pirate"></i>
                            @foreach (var users in Model)
                            {
                                @if (users.User.RememberMe == true)
                                {
                                    <audio controls autoplay hidden>
                                        <source src="~/sounds/carstart.mp3" type="audio/mp3">
                                        Your browser does not support the audio element.
                                    </audio>
                                }
                            }
                        }
                        @if (session.GetName() == "MARIKKAKAY@YAHOO.COM")
                        {
                            <i class="mdi mdi-cow"></i>
                            @foreach (var users in Model)
                            {
                                @if (users.User.RememberMe == true)
                                {
                                    <audio controls autoplay hidden>
                                        <source src="~/sounds/cow.mp3" type="audio/mp3">
                                        Your browser does not support the audio element.
                                    </audio>
                                }
                            }
                        }
                        @if (session.GetName() == "PR@CAMPCHETEK.ORG")
                        {
                            <i class="mdi mdi-castle"></i>
                            @foreach (var users in Model)
                            {
                                @if (users.User.RememberMe == true)
                                {
                                    <audio controls autoplay hidden>
                                        <source src="~/sounds/service-bell_daniel_simion.mp3" type="audio/mp3">
                                        Your browser does not support the audio element.
                                    </audio>
                                }
                            }
                        }

                        <span class="sidebar__nav__text">@(session.GetName() == null ? "Logout" : session.GetName())</span>
                    </a>                 
                </li>   
                         <li>
                           <a  asp-area="Admin" asp-controller="Housing" asp-action="Settings" class="sidebar__nav__link">
                                <i class="mdi mdi-settings"></i>
                                <span class="sidebar__nav__text">Settings</span>
                           </a>
                         </li>
            </ul>
        </nav>
    </aside>
    <div class="text-center">
        <h1 class="newUser">Houseing Request</h1>
        <a class="submit-btn" style="text-align:center" asp-area="Admin" asp-controller="Housing" asp-action="NewSubmission">New Request</a>
    </div>
<table class="table table-bordered table-striped" style="background-color: white">
    <thead>
        <tr>
            <th>ID</th>
            <th>@Html.ActionLink("First Name", "Dashboard", new { orderby = ViewBag.FirstNameSortParm })</th>
            <th>@Html.ActionLink("Last Name", "Dashboard", new { orderby = ViewBag.LastNameParm })</th>
            <th>City</th>
            <th>State</th>
            <th>@Html.ActionLink("Room", "Dashboard", new { orderby = ViewBag.RoomsIdParm })</th>
            <th>@Html.ActionLink("Arrival", "Dashboard", new { orderby = ViewBag.ArrivalDateParm })</th>
            <th>@Html.ActionLink("Departure", "Dashboard", new { orderby = ViewBag.DepartureDateParm })</th>
            <th>@Html.ActionLink("# Of Guest", "Dashboard", new { orderby = ViewBag.NumberGuestParm })</th>
            <th>@Html.ActionLink("Bedding", "Dashboard", new { orderby = ViewBag.BeddingParm })</th>
            <th>@Html.ActionLink("Date Updated", "Dashboard", new { orderby = ViewBag.DateUpdateParm })</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var housing in @Model)
        {
            <tr>
                <td>@housing.event_id</td>
                <td>@housing.FirstName</td>
                <td>@housing.LastName</td>
                <td>@housing.City</td>
                <td>@housing.State</td>
                <td>@housing.Rooms.Name</td>
                <td>@housing.event_start</td>
                <td>@housing.event_end</td>
                <td>@housing.NumberGuest</td>
                <td>@housing.Bedding.Name</td>
                <td>@housing.DateUpdate</td>
                <td>
                    <a asp-area="Admin" asp-action="Detail" asp-route-id="@housing.event_id"><img src="~/img/edit.png" alt="View" style="width:24px; height:24px;" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>

Areas/Admin/Views/Housing/Delete.cshtml
@model Events
@{
    Layout = "_EditLayout";
    ViewBag.FirstName = "Delete Request";
    var session = new HousingSession(Context.Session);
}
<aside class="sidebar">
    <nav>
        <ul class="sidebar__nav">
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Dashboard" class="sidebar__nav__link">
                    <i class="mdi mdi-home-export-outline"></i>
                    <span class="sidebar__nav__text">Home</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Events" asp-action="Calendar" class="sidebar__nav__link">
                    <i class="mdi mdi-calendar-month"></i>
                    <span class="sidebar__nav__text">Calendar</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Add" class="sidebar__nav__link">
                    <i class="mdi mdi-plus-outline"></i>
                    <span class="sidebar__nav__text">Add</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="RoomStatus" class="sidebar__nav__link">
                    <i class="mdi mdi-file-document-box"></i>
                    <span class="sidebar__nav__text">Room Status</span>
                </a>
            </li>
            <li>

                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="sidebar__nav__link">

                    @if (session.GetName() == "DANAEL@CAMPCHETEK.ORG")
                    {
                        <i class="mdi mdi-pirate"></i>

                    }
                    @if (session.GetName() == "MARIKKAKAY@YAHOO.COM")
                    {
                        <i class="mdi mdi-cow"></i>

                    }
                    @if (session.GetName() == "PR@CAMPCHETEK.ORG")
                    {
                        <i class="mdi mdi-castle"></i>
                       
                    }

                    <span class="sidebar__nav__text">@(session.GetName() == null ? "Logout" : session.GetName())</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Settings" class="sidebar__nav__link">
                    <i class="mdi mdi-settings"></i>
                    <span class="sidebar__nav__text">Settings</span>
                </a>
            </li>
        </ul>
    </nav>
</aside>
<section class="get-in-touch">
    <h1 class="title">Delete</h1>
    <form asp-action="Delete" method="post" class="contact-form row">
        <div action="/" class="form-field col-lg-6">
            <input asp-for="event_start" type="date" class="input-text js-input" />
            <label class="label" asp-for="event_start">Arrival Date:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="event_end" type="date" class="input-text js-input" />
            <label class="label" asp-for="event_end">Departure Date:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="FirstName" class="input-text js-input" />
            <label class="label" asp-for="FirstName">First Name:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="LastName" class="input-text js-input" />
            <label class="label" asp-for="LastName">Last Name:</label>
        </div>
        <div class="form-field col-lg-6">
            <select asp-for="ReasonId" class="input-text js-input">
                <option value=""></option>
                @foreach (Reason r in ViewBag.Reason)
                {
                    <option value="@r.ReasonId">@r.Name</option>
                }
            </select>
            <label class="label" asp-for="ReasonId">Reason For Stay</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="Email" class="input-text js-input" />
            <label class="label" asp-for="Email">Email:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="Address" class="input-text js-input" />
            <label class="label" asp-for="Address">Address:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="City" class="input-text js-input" />
            <label class="label" asp-for="City">City:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="State" class="input-text js-input" />
            <label class="label" asp-for="State">State:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="Zip" class="input-text js-input" />
            <label class="label" asp-for="Zip">Zip:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="Phone" class="input-text js-input" disabled />
            <label class="label" asp-for="Phone">Phone:</label>
        </div>
        <div class="form-field col-lg-6">
            <select asp-for="BeddingId" class="input-text js-input" disabled>
                <option value=""></option>
                @foreach (Bedding b in ViewBag.Bedding)
                {
                    <option value="@b.BeddingId">@b.Name</option>
                }
            </select>
            <label class="label" asp-for="BeddingId">Select If Need Bedding:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="NumberGuest" class="input-text js-input" type="number" min="1" max="13" disabled>
            <label asp-for="NumberGuest" class="label">Total Number Of Guest</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="Message" class="input-text js-input" type="text" disabled>
            <label class="label" asp-for="Message">Any Special Needs</label>
        </div>
        <div class="form-field col-lg-12">
            <select asp-for="RoomsId" class="input-text js-input" disabled>
                <option value=""></option>
                @foreach (Rooms r in ViewBag.Rooms)
                {
                    <option value="@r.RoomsId">@r.Name</option>
                }
            </select>
            <label class="label" asp-for="RoomsId">Select a Room:</label>
        </div>
        <div class="form-field col-lg-6">
            <input asp-for="sendEmail" class="input-text js-input" type="checkbox" />
            <label class="label" asp-for="sendEmail">Send Email:</label>
        </div>
        <input type="hidden" asp-for="UserId" value="3" />
        <input type="hidden" asp-for="event_id" />
        <div class="form-field col-lg-12">
            <button type="submit" class="submit-btn">Delete</button>
            <a class="submit-btn" style="text-align:center" asp-area="Admin" asp-controller="Housing" asp-action="Dashboard">Cancel</a>
        </div>
    </form>
</section>

Areas/Admin/Views/Housing/Detail.cshtml
@model Events
@{
    //Layout = "Sidebar";
    ViewData["Title"] = "Detail";
    var session = new HousingSession(Context.Session);

}
<aside class="sidebar">
    <nav>
        <ul class="sidebar__nav">
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Dashboard" class="sidebar__nav__link">
                    <i class="mdi mdi-home-export-outline"></i>
                    <span class="sidebar__nav__text">Home</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Events" asp-action="Calendar" class="sidebar__nav__link">
                    <i class="mdi mdi-calendar-month"></i>
                    <span class="sidebar__nav__text">Calendar</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Add" class="sidebar__nav__link">
                    <i class="mdi mdi-plus-outline"></i>
                    <span class="sidebar__nav__text">Add</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="RoomStatus" class="sidebar__nav__link">
                    <i class="mdi mdi-file-document-box"></i>
                    <span class="sidebar__nav__text">Room Status</span>
                </a>
            </li>
            <li>

                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="sidebar__nav__link">

                    @if (session.GetName() == "DANAEL@CAMPCHETEK.ORG")
                    {
                        <i class="mdi mdi-pirate"></i>

                    }
                    @if (session.GetName() == "MARIKKAKAY@YAHOO.COM")
                    {
                        <i class="mdi mdi-cow"></i>

                    }
                    @if (session.GetName() == "PR@CAMPCHETEK.ORG")
                    {
                        <i class="mdi mdi-castle"></i>

                    }

                    <span class="sidebar__nav__text">@(session.GetName() == null ? "Logout" : session.GetName())</span>
                </a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Housing" asp-action="Settings" class="sidebar__nav__link">
                    <i class="mdi mdi-settings"></i>
                    <span class="sidebar__nav__text">Settings</span>
                </a>
            </li>
        </ul>
    </nav>
</aside>

<div class="main">
    <div class="text-center">
        <h1>Detail</h1>
    </div>
    <table class="table table-bordered table-striped" style="background-color: white">
        <tr>
            <td><strong>ID:</strong></td>
            <td>@Model.event_id</td>
        </tr>
        <tr>
            <td><strong>Arrival Date:</strong></td>
            <td>@Model.event_start</td>
        </tr>
        <tr>
            <td><strong>Departure Date:</strong></td>
            <td>@Model.event_end</td>
        </tr>
        <tr>
            <td><strong>Reason For Stay:</strong></td>
            <td>@Model.Reason.Name</td>
        </tr>
        <tr>
            <td><strong>First Name:</strong></td>
            <td>@Model.FirstName</td>
        </tr>
        <tr>
            <td><strong>Last Name:</strong></td>
            <td>@Model.LastName</td>
        </tr>
        <tr>
            <td><strong>Email:</strong></td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td><strong>Address:</strong></td>
            <td>@Model.Address</td>
        </tr>
        <tr>
            <td><strong>City:</strong></td>
            <td>@Model.City</td>
        </tr>
        <tr>
            <td><strong>State:</strong></td>
            <td>@Model.State</td>
        </tr>
        <tr>
            <td><strong>Zip:</strong></td>
            <td>@Model.Zip</td>
        </tr>
        <tr>
            <td><strong>Phone:</strong></td>
            <td>@Model.Phone</td>
        </tr>
        <tr>
            <td><strong>Bedding:</strong></td>
            <td>@Model.Bedding.Name</td>
        </tr>
        <tr>
            <td><strong>Number Of Guest:</strong></td>
            <td>@Model.NumberGuest</td>
        </tr>
        <tr>
            <td><strong>Message:</strong></td>
            <td>@Model.Message</td>
        </tr>
        <tr>
            <td><strong>Room:</strong></td>
            <td>@Model.Rooms.Name</td>
        </tr>
        <tr>
            <td><strong>Updated By:</strong></td>
            <td>@Model.User.FirstName @Model.User.LastName</td>
        </tr>
        <tr>
            <td><strong>Updated Time:</strong></td>
            <td>@Model.DateUpdate</td>
        </tr>
    </table>
    <a class="btn btn-white ml-2" asp-area="Admin" asp-controller="Housing" asp-action="Dashboard">Close</a>
    <a class="btn btn-white ml-2" asp-area="Admin" asp-controller="Housing" asp-action="Edit" asp-route-id="@Model.event_id">Edit</a>
    <a class="btn btn-white ml-2" asp-area="Admin" asp-controller="Housing" asp-action="Delete" asp-route-id="@Model.event_id">Delete</a>
</div>